	/**
	 * Module: RTC
	 * ===========
	 */

		//#define RTC_HW DS3231
		#define RTC_I2C_ADDRESS 0x68

		#define RTC_DAYS "Do\0", "Lu\0", "Ma\0", "Mi\0", "Ju\0", "Vi\0", "Sa\0"

	/**
	 * OneWireSwitches configuration
	 */

		#define RTC_BUTTON_CONFIGURE_ID TEMPERATURE_BUTTON_STARTSTOPDIRECTION_ID
		#define RTC_BUTTON_CONFIGURE_DELAY 1000
		#define RTC_BUTTON_CONFIGURE_BUZZER_TIME 25

		#define RTC_BUTTON_MINUS_ID TEMPERATURE_BUTTON_MINUS_ID
		#define RTC_BUTTON_MINUS_THRESHOLD 50

		#define RTC_BUTTON_PLUS_ID TEMPERATURE_BUTTON_PLUS_ID
		#define RTC_BUTTON_PLUS_THRESHOLD 50

		#define RTC_BUTTON_NEXT_ID TEMPERATURE_BUTTON_STARTSTOPDIRECTION_ID
		#define RTC_BUTTON_NEXT_THRESHOLD 100
		#define RTC_BUTTON_NEXT_DELAY 250
		#define RTC_BUTTON_NEXT_BUZZER_TIME 25